"""add function_name to problems

Revision ID: 4e3a137254bb
Revises: a9e6137cbc8c
Create Date: 2026-09-04 23:09:47.481081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3a137254bb'
down_revision: Union[str, Sequence[str], None] = 'a9e6137cbc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('function_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'function_name')
    # ### end Alembic commands ###
