"""add coding_sessions table

Revision ID: 6a2e05205f24
Revises: 4e6e7dfac2d8
Create Date: 2026-08-27 15:17:02.687246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2e05205f24'
down_revision: Union[str, Sequence[str], None] = '4e6e7dfac2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('current_code', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_sessions_id'), 'coding_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_coding_sessions_problem_id'), 'coding_sessions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_coding_sessions_user_id'), 'coding_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coding_sessions_user_id'), table_name='coding_sessions')
    op.drop_index(op.f('ix_coding_sessions_problem_id'), table_name='coding_sessions')
    op.drop_index(op.f('ix_coding_sessions_id'), table_name='coding_sessions')
    op.drop_table('coding_sessions')
    # ### end Alembic commands ###
