"""add analysis_reports table

Revision ID: 7a906e02b914
Revises: e90f4e665fe5
Create Date: 2026-09-02 01:28:15.929469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a906e02b914'
down_revision: Union[str, Sequence[str], None] = 'e90f4e665fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coding_session_id', sa.Integer(), nullable=False),
    sa.Column('correctness_score', sa.Float(), nullable=True),
    sa.Column('code_quality_score', sa.Float(), nullable=True),
    sa.Column('edge_case_score', sa.Float(), nullable=True),
    sa.Column('time_complexity', sa.String(length=50), nullable=True),
    sa.Column('space_complexity', sa.String(length=50), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('optimization_suggestions', sa.Text(), nullable=True),
    sa.Column('code_explanation', sa.Text(), nullable=True),
    sa.Column('interview_questions', sa.Text(), nullable=True),
    sa.Column('full_report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coding_session_id'], ['coding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_coding_session_id'), 'analysis_reports', ['coding_session_id'], unique=True)
    op.create_index(op.f('ix_analysis_reports_id'), 'analysis_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_reports_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_coding_session_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
