"""add problem_test_cases table

Revision ID: 98efc8d6cbfd
Revises: 7a906e02b914
Create Date: 2026-09-03 01:57:33.416312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98efc8d6cbfd'
down_revision: Union[str, Sequence[str], None] = '7a906e02b914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_test_cases_id'), 'problem_test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_problem_test_cases_problem_id'), 'problem_test_cases', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_test_cases_problem_id'), table_name='problem_test_cases')
    op.drop_index(op.f('ix_problem_test_cases_id'), table_name='problem_test_cases')
    op.drop_table('problem_test_cases')
    # ### end Alembic commands ###
