"""link conversation to coding session

Revision ID: e90f4e665fe5
Revises: 6a2e05205f24
Create Date: 2026-08-27 16:44:29.304189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90f4e665fe5'
down_revision: Union[str, Sequence[str], None] = '6a2e05205f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('coding_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_coding_session_id'), 'conversations', ['coding_session_id'], unique=True)
    op.create_foreign_key(None, 'conversations', 'coding_sessions', ['coding_session_id'], ['id'], ondelete='CASCADE')
    op.add_column('messages', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('messages', sa.Column('content', sa.Text(), nullable=False))
    op.alter_column('messages', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('messages', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'role')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_coding_session_id'), table_name='conversations')
    op.drop_column('conversations', 'coding_session_id')
    # ### end Alembic commands ###
